describe('Prueba de aceptación sobre una interfaz externa de demostración', () => {
    it('interactúa con controles del sitio de ejemplo de Cypress', () => {
    cy.visit('https://example.cypress.io/commands/actions')
    cy.get('.action-email')
    .type('estudiante@example.com')
    .should('have.value', 'estudiante@example.com')
    cy.get('.action-checkboxes [type="checkbox"]')
    .first()
    .check()
    .should('be.checked')
    cy.get('.action-select')
    .select('apples')
    .should('have.value', 'fr-apples')
    })
   })
